/**
 * Additive migration: platform superadmin + settings + password reset.
 * Safe to re-run (IF NOT EXISTS / ON CONFLICT).
 *
 * Run: npm run db:superadmin
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";
import { hashPassword } from "../lib/auth";

async function columnExists(table: string, column: string): Promise<boolean> {
  const { rowCount } = await pool.query(
    `SELECT 1
     FROM information_schema.columns
     WHERE table_schema = current_schema()
       AND table_name = $1
       AND column_name = $2`,
    [table, column],
  );
  return (rowCount ?? 0) > 0;
}

export async function migrateSuperadmin(options: DbTaskOptions = {}) {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    if (!(await columnExists("users", "is_platform_admin"))) {
      await client.query(
        `ALTER TABLE users
         ADD COLUMN is_platform_admin BOOLEAN NOT NULL DEFAULT FALSE`,
      );
      console.log("Added users.is_platform_admin");
    }

    if (!(await columnExists("users", "username"))) {
      await client.query(`ALTER TABLE users ADD COLUMN username VARCHAR(100)`);
      console.log("Added users.username");
    }

    await client.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username
      ON users (username)
      WHERE username IS NOT NULL
    `);

    await client.query(`
      CREATE TABLE IF NOT EXISTS password_reset_tokens (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        token VARCHAR(128) NOT NULL UNIQUE,
        expires_at TIMESTAMP NOT NULL,
        used_at TIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_password_reset_user
      ON password_reset_tokens(user_id)
    `);

    await client.query(`
      CREATE TABLE IF NOT EXISTS platform_settings (
        setting_key VARCHAR(100) PRIMARY KEY,
        setting_value TEXT NOT NULL,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
      )
    `);

    const defaults: [string, string][] = [
      ["ai_model_id", process.env.BEDROCK_MODEL_ID?.trim() || "amazon.nova-lite-v1:0"],
      ["platform_fee_percent", "15"],
      ["email_provider", "ses"],
      ["smtp_host", ""],
      ["smtp_port", "587"],
      ["smtp_user", ""],
      ["smtp_pass", ""],
      ["smtp_from", ""],
      ["smtp_secure", "false"],
    ];

    for (const [key, value] of defaults) {
      await client.query(
        `INSERT INTO platform_settings (setting_key, setting_value)
         VALUES ($1, $2)
         ON CONFLICT (setting_key) DO NOTHING`,
        [key, value],
      );
    }

    const username = (process.env.SUPERADMIN_USERNAME ?? "superadmin").trim().toLowerCase();
    const password = process.env.SUPERADMIN_PASSWORD ?? "SuperAdmin123!";
    const email = (
      process.env.SUPERADMIN_EMAIL ?? "superadmin@forkup.local"
    )
      .trim()
      .toLowerCase();
    const fullName = process.env.SUPERADMIN_FULL_NAME ?? "ForkUp Super Admin";

    const { rows: existing } = await client.query<{ id: number }>(
      `SELECT id FROM users
       WHERE LOWER(email) = $1 OR LOWER(COALESCE(username, '')) = $2
       LIMIT 1`,
      [email, username],
    );

    if (existing.length === 0) {
      const passwordHash = await hashPassword(password);
      await client.query(
        `INSERT INTO users (email, password_hash, full_name, username, is_platform_admin)
         VALUES ($1, $2, $3, $4, TRUE)`,
        [email, passwordHash, fullName, username],
      );
      console.log(`Created platform superadmin user "${username}" (${email}).`);
    } else {
      await client.query(
        `UPDATE users
         SET is_platform_admin = TRUE,
             username = COALESCE(username, $2),
             updated_at = NOW()
         WHERE id = $1`,
        [existing[0].id, username],
      );
      console.log(`Ensured user id=${existing[0].id} is platform superadmin.`);
    }

    await client.query("COMMIT");
    console.log("Superadmin migration complete.");
  } catch (err) {
    await client.query("ROLLBACK");
    throw err;
  } finally {
    client.release();
    if (options.closePool !== false) {
      await pool.end();
    }
  }
}

if (isDirectRun(import.meta.url)) {
  migrateSuperadmin().catch((err) => {
    console.error("Superadmin migration failed:", err);
    process.exit(1);
  });
}
