/**
 * Additive migration: pre-campaign AI analysis sessions + campaign idea cards.
 *
 * Supports the AI-first create flow:
 * - Backend Steps 3–4 (website/social analyze) persist here — no dedicated UI.
 * - Step 5 idea picker resumes via session_token.
 * Guest campaign draft body stays in browser localStorage (not stored here).
 *
 * Inputs: none (DDL only). Outputs: two new tables + indexes/trigger.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const AI_CAMPAIGN_FLOW_DDL = `
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS organization_ai_analysis_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_token VARCHAR(64) NOT NULL UNIQUE,
  nonprofit_id INTEGER NULL,
  organization_name VARCHAR(255) NOT NULL,
  ein VARCHAR(20),
  website VARCHAR(512),
  facebook_url VARCHAR(512),
  instagram_url VARCHAR(512),
  linkedin_url VARCHAR(512),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  analysis_json JSON,
  error_message TEXT,
  created_by_user_id INTEGER NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_org_ai_analysis_nonprofit
    FOREIGN KEY (nonprofit_id) REFERENCES nonprofits(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_org_ai_analysis_token
  ON organization_ai_analysis_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_org_ai_analysis_nonprofit
  ON organization_ai_analysis_sessions(nonprofit_id);
CREATE INDEX IF NOT EXISTS idx_org_ai_analysis_expires
  ON organization_ai_analysis_sessions(expires_at);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_org_ai_analysis_updated_at'
  ) THEN
    CREATE TRIGGER trg_org_ai_analysis_updated_at
      BEFORE UPDATE ON organization_ai_analysis_sessions
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS organization_ai_campaign_ideas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_session_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  confidence INTEGER NOT NULL DEFAULT 0
    CHECK (confidence >= 0 AND confidence <= 100),
  thumbnail_url VARCHAR(512),
  suggested_goal NUMERIC(12, 2),
  suggested_methods JSON,
  payload_json JSON,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_org_ai_ideas_session
    FOREIGN KEY (analysis_session_id)
    REFERENCES organization_ai_analysis_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_org_ai_ideas_session
  ON organization_ai_campaign_ideas(analysis_session_id, sort_order);
`;

export async function migrateAiCampaignFlow(options: DbTaskOptions = {}) {
  await pool.query(AI_CAMPAIGN_FLOW_DDL);
  console.log(
    "ForkUp AI campaign flow schema applied (organization_ai_analysis_sessions, organization_ai_campaign_ideas).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateAiCampaignFlow().catch((err) => {
    console.error("AI campaign flow migration failed:", err);
    process.exit(1);
  });
}
