/**
 * Additive migration: pending signups (email stored only after verification).
 *
 * Purpose: Hold signup credentials + verification token/code without creating a
 * users row until the email is verified. Prevents abandoned signups from
 * blocking the email address.
 *
 * Inputs: none (DDL only).
 * Outputs: pending_signups table + indexes. No changes to existing users rows.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const PENDING_SIGNUPS_DDL = `
CREATE TABLE IF NOT EXISTS pending_signups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  organization_type VARCHAR(20)
    CHECK (organization_type IS NULL OR organization_type IN ('nonprofit', 'business')),
  organization_id INTEGER,
  organization_role VARCHAR(20)
    CHECK (organization_role IS NULL OR organization_role IN ('owner', 'admin', 'manager', 'viewer')),
  token VARCHAR(128) NOT NULL UNIQUE,
  code VARCHAR(10) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pending_signups_email_active
  ON pending_signups (LOWER(email))
  WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_pending_signups_code
  ON pending_signups (code)
  WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_pending_signups_token
  ON pending_signups (token);
`;

/**
 * Apply pending_signups table for verify-before-create registration.
 *
 * Inputs: options.closePool — whether to end the pool (default true when run directly).
 * Outputs: void; logs success; additive only.
 */
export async function migratePendingSignups(options: DbTaskOptions = {}) {
  await pool.query(PENDING_SIGNUPS_DDL);
  console.log(
    "ForkUp pending_signups applied (verify-before-create signup staging table).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migratePendingSignups().catch((err) => {
    console.error("pending_signups migration failed:", err);
    process.exit(1);
  });
}
