/**
 * Additive migration: AI-native Success Engine support (Nick V2 Layer 4).
 *
 * - Extends success_engine_actions.action_type CHECK with calendar band types
 * - Adds stakeholder_role + generated_by on success_engine_actions
 * - Creates campaign_ai_insights log table
 *
 * Inputs: none (DDL only). Outputs: schema applied with safe defaults.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const CAMPAIGN_AI_DDL = `
ALTER TABLE success_engine_actions
  DROP CONSTRAINT IF EXISTS success_engine_actions_action_type_check;

ALTER TABLE success_engine_actions
  ADD CONSTRAINT success_engine_actions_action_type_check
  CHECK (action_type IN (
    'launch_email',
    'one_week_reminder',
    'mid_campaign_reminder',
    'final_push_reminder',
    'results_email',
    'ambassador_recruitment',
    'guest_bartender_recruitment',
    'business_promotion',
    'receipt_reminder',
    'business_invite_reminder',
    'nonprofit_announcement',
    'staff_talking_points',
    'social_post',
    'countdown_reminder',
    'day_of_reminder',
    'thank_you',
    'settlement_recap',
    'rebooking_prompt',
    'admin_review_summary'
  ));

ALTER TABLE success_engine_actions
  ADD COLUMN IF NOT EXISTS stakeholder_role VARCHAR(20);

ALTER TABLE success_engine_actions
  DROP CONSTRAINT IF EXISTS success_engine_actions_stakeholder_role_check;

ALTER TABLE success_engine_actions
  ADD CONSTRAINT success_engine_actions_stakeholder_role_check
  CHECK (
    stakeholder_role IS NULL OR stakeholder_role IN (
      'nonprofit', 'business', 'ambassador', 'supporter', 'admin'
    )
  );

ALTER TABLE success_engine_actions
  ADD COLUMN IF NOT EXISTS generated_by VARCHAR(20) NOT NULL DEFAULT 'system';

ALTER TABLE success_engine_actions
  DROP CONSTRAINT IF EXISTS success_engine_actions_generated_by_check;

ALTER TABLE success_engine_actions
  ADD CONSTRAINT success_engine_actions_generated_by_check
  CHECK (generated_by IN ('system', 'ai', 'manual'));

CREATE TABLE IF NOT EXISTS campaign_ai_insights (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  insight_type VARCHAR(40) NOT NULL
    CHECK (insight_type IN (
      'timing_guidance',
      'method_mix',
      'invite_readiness',
      'business_recommendations',
      'health_nudge',
      'admin_review',
      'settlement_narrative',
      'calendar_plan'
    )),
  score INTEGER,
  summary TEXT NOT NULL,
  payload_json JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_insights_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_ai_insights_campaign
  ON campaign_ai_insights(campaign_id);
`;

export async function migrateCampaignAi(options: DbTaskOptions = {}) {
  await pool.query(CAMPAIGN_AI_DDL);
  console.log(
    "ForkUp campaign AI schema applied (SE action types, stakeholder_role, campaign_ai_insights).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateCampaignAi().catch((err) => {
    console.error("Campaign AI migration failed:", err);
    process.exit(1);
  });
}
