import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const AUTOMATION_DDL = `
CREATE TABLE IF NOT EXISTS automation_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_source VARCHAR(30) NOT NULL DEFAULT 'cron'
    CHECK (trigger_source IN ('cron', 'manual', 'api')),
  actions_processed INTEGER NOT NULL DEFAULT 0,
  emails_sent INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  ran_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_automation_runs_ran_at ON automation_runs(ran_at);

ALTER TABLE success_engine_actions
  ADD COLUMN IF NOT EXISTS auto_send BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE success_engine_actions
  ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP;
ALTER TABLE success_engine_actions
  ADD COLUMN IF NOT EXISTS last_error TEXT;
`;

export async function migrateAutomation(options: DbTaskOptions = {}) {
  await pool.query(AUTOMATION_DDL);
  console.log(
    "ForkUp automation schema applied (automation_runs + success_engine_actions.auto_send/sent_at/last_error).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateAutomation().catch((err) => {
    console.error("Automation migration failed:", err);
    process.exit(1);
  });
}
