/**
 * Additive migration: user email verification on signup.
 *
 * Purpose: Track whether a user has verified their email, and store
 * short-lived verification tokens (URL token + 6-digit code).
 *
 * Inputs: none (DDL + safe backfill for existing users).
 * Outputs: users.email_verified_at (nullable), email_verification_tokens table.
 * Existing accounts are marked verified so current sign-in is unchanged.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const EMAIL_VERIFICATION_DDL = `
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token VARCHAR(128) NOT NULL UNIQUE,
  code VARCHAR(10),
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_email_verification_user
  ON email_verification_tokens (user_id);

CREATE INDEX IF NOT EXISTS idx_email_verification_code
  ON email_verification_tokens (code)
  WHERE code IS NOT NULL;
`;

/**
 * Apply email verification columns/tables and backfill existing users as verified.
 *
 * Inputs: options.closePool — whether to end the pool (default true when run directly).
 * Outputs: void; logs success; additive only (no DROP/RENAME).
 */
export async function migrateEmailVerification(options: DbTaskOptions = {}) {
  await pool.query(EMAIL_VERIFICATION_DDL);

  // Existing accounts must keep working — treat them as already verified.
  const backfill = await pool.query(
    `UPDATE users
     SET email_verified_at = COALESCE(created_at, NOW())
     WHERE email_verified_at IS NULL`,
  );
  console.log(
    `ForkUp email verification applied (users.email_verified_at + email_verification_tokens). Backfilled ${backfill.rowCount ?? 0} existing user(s).`,
  );

  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateEmailVerification().catch((err) => {
    console.error("email verification migration failed:", err);
    process.exit(1);
  });
}
