import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const LIBRARY_DDL = `
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS organization_library_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_type VARCHAR(20) NOT NULL
    CHECK (organization_type IN ('nonprofit', 'business')),
  organization_id INTEGER NOT NULL,
  category VARCHAR(40) NOT NULL,
  title VARCHAR(255),
  description TEXT,
  content TEXT,
  asset_url VARCHAR(512),
  source VARCHAR(20) NOT NULL DEFAULT 'manual'
    CHECK (source IN ('manual', 'website_scan', 'social_scan', 'import')),
  source_url VARCHAR(512),
  review_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'approved', 'rejected', 'ignored')),
  metadata_json JSON,
  created_by_user_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_org_library_org
  ON organization_library_items(organization_type, organization_id);
CREATE INDEX IF NOT EXISTS idx_org_library_review
  ON organization_library_items(review_status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_org_library_updated_at') THEN
    CREATE TRIGGER trg_org_library_updated_at
      BEFORE UPDATE ON organization_library_items
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;
`;

export async function migrateLibrary(options: DbTaskOptions = {}) {
  await pool.query(LIBRARY_DDL);
  console.log("ForkUp organization library schema applied (organization_library_items).");
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateLibrary().catch((err) => {
    console.error("Library migration failed:", err);
    process.exit(1);
  });
}
