/**
 * Additive migration: nonprofit ACH bank fields + settlement ACH approval tokens.
 *
 * Purpose:
 * - Task 19: mirror business location ACH columns on nonprofits for NPO payouts.
 * - Task 17/20: settlement_ach_approvals for invoice → link → approve → ACH flow.
 *
 * Inputs: none (DDL only). Outputs: nullable/defaulted columns and new table.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const SETTLEMENT_ACH_FLOW_DDL = `
ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_bank_name VARCHAR(150);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_account_holder_name VARCHAR(150);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_account_type VARCHAR(20);

ALTER TABLE nonprofits
  DROP CONSTRAINT IF EXISTS np_ach_account_type_check;

ALTER TABLE nonprofits
  ADD CONSTRAINT np_ach_account_type_check
  CHECK (ach_account_type IS NULL OR ach_account_type IN ('checking', 'savings'));

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_routing_number VARCHAR(500);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_account_number VARCHAR(500);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_account_last4 VARCHAR(4);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_authorization_status VARCHAR(20) NOT NULL DEFAULT 'pending';

ALTER TABLE nonprofits
  DROP CONSTRAINT IF EXISTS np_ach_authorization_status_check;

ALTER TABLE nonprofits
  ADD CONSTRAINT np_ach_authorization_status_check
  CHECK (ach_authorization_status IN ('pending', 'authorized', 'revoked'));

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_authorized_by VARCHAR(150);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_authorized_email VARCHAR(150);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_authorized_at TIMESTAMP;

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_last_updated_at TIMESTAMP;

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_signature_path VARCHAR(512);

ALTER TABLE nonprofits
  ADD COLUMN IF NOT EXISTS ach_contact_email VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_nonprofits_ach_status
  ON nonprofits(ach_authorization_status);

CREATE TABLE IF NOT EXISTS settlement_ach_approvals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  settlement_id INTEGER NOT NULL,
  campaign_id INTEGER NOT NULL,
  approval_type VARCHAR(30) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  approval_token VARCHAR(64) NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  approved_by_name VARCHAR(150),
  approved_by_email VARCHAR(255),
  approved_at TIMESTAMP,
  ach_initiated_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_settlement_ach_approval_settlement
    FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE CASCADE,
  CONSTRAINT fk_settlement_ach_approval_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT settlement_ach_approval_type_check
    CHECK (approval_type IN ('business_debit', 'nonprofit_payout')),
  CONSTRAINT settlement_ach_approval_status_check
    CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_settlement_ach_approval_settlement_type
  ON settlement_ach_approvals(settlement_id, approval_type);

CREATE INDEX IF NOT EXISTS idx_settlement_ach_approval_token
  ON settlement_ach_approvals(approval_token);
`;

export async function migrateSettlementAchFlow(options: DbTaskOptions = {}) {
  await pool.query(SETTLEMENT_ACH_FLOW_DDL);
  console.log(
    "ForkUp settlement ACH flow schema applied (nonprofit ACH columns + settlement_ach_approvals).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateSettlementAchFlow().catch((err) => {
    console.error("Settlement ACH flow migration failed:", err);
    process.exit(1);
  });
}
