/**
 * Additive migration: business → NPO campaign partner join requests.
 *
 * Purpose: Let restaurants / local businesses request to join an existing
 * public campaign. NPO accepts or declines; on accept, backend will create
 * the normal campaign_business_locations invite path (separate pass).
 *
 * Supports both:
 * - Existing ForkUp businesses (authenticated)
 * - New-to-ForkUp businesses (after guest join / signup / claim)
 *
 * Inputs: none (uses pool).
 * Outputs: campaign_partner_join_requests table. Existing rows unchanged.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

/**
 * Full DDL (additive only). Safe to re-run:
 * - CREATE TABLE IF NOT EXISTS
 * - CREATE INDEX IF NOT EXISTS
 * - CREATE UNIQUE INDEX IF NOT EXISTS (partial)
 */
export const CAMPAIGN_PARTNER_JOIN_REQUESTS_DDL = `
CREATE TABLE IF NOT EXISTS campaign_partner_join_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  business_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  method_id INTEGER NOT NULL,
  method_type VARCHAR(40) NOT NULL
    CHECK (method_type IN (
      'dine_and_donate',
      'shop_and_donate',
      'service_giveback',
      'guest_bartending_event'
    )),
  door_type VARCHAR(20) NULL
    CHECK (door_type IS NULL OR door_type IN ('restaurant', 'local')),
  request_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (request_status IN ('pending', 'accepted', 'declined')),
  proposed_giveback_percentage DECIMAL(5,2) NULL,
  message TEXT NULL,
  requested_by_user_id INTEGER NULL,
  campaign_business_location_id INTEGER NULL,
  responded_at TIMESTAMP NULL,
  responded_by_user_id INTEGER NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cpjr_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_cpjr_business
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
  CONSTRAINT fk_cpjr_location
    FOREIGN KEY (location_id) REFERENCES business_locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_cpjr_method
    FOREIGN KEY (method_id) REFERENCES campaign_methods(id) ON DELETE CASCADE,
  CONSTRAINT fk_cpjr_requested_by
    FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cpjr_responded_by
    FOREIGN KEY (responded_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cpjr_cbl
    FOREIGN KEY (campaign_business_location_id)
    REFERENCES campaign_business_locations(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_cpjr_campaign_status
  ON campaign_partner_join_requests(campaign_id, request_status);

CREATE INDEX IF NOT EXISTS idx_cpjr_business_status
  ON campaign_partner_join_requests(business_id, request_status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cpjr_pending_partner
  ON campaign_partner_join_requests (campaign_id, business_id, location_id, method_id)
  WHERE request_status = 'pending';

COMMENT ON TABLE campaign_partner_join_requests IS
  'Business-initiated request to join an existing campaign; NPO accepts/declines.';
`;

/**
 * Apply campaign partner join-request table.
 * Inputs: options.closePool — end pool when run directly (default true).
 * Outputs: void; additive only.
 */
export async function migrateCampaignPartnerJoinRequests(
  options: DbTaskOptions = {},
) {
  await pool.query(CAMPAIGN_PARTNER_JOIN_REQUESTS_DDL);
  console.log(
    "ForkUp campaign_partner_join_requests schema applied (pending unique per campaign+business+location+method).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateCampaignPartnerJoinRequests().catch((err) => {
    console.error("campaign partner join requests migration failed:", err);
    process.exit(1);
  });
}
