import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const PAYOUTS_DDL = `
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS payouts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  settlement_id INTEGER,
  business_id INTEGER,
  location_id INTEGER,
  payout_type VARCHAR(30) NOT NULL DEFAULT 'forkup_to_nonprofit'
    CHECK (payout_type IN ('business_to_forkup', 'forkup_to_nonprofit', 'adjustment')),
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'paid', 'failed', 'cancelled')),
  method VARCHAR(20)
    CHECK (method IN ('ach', 'check', 'manual', 'other')),
  reference VARCHAR(255),
  notes TEXT,
  initiated_at TIMESTAMP,
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payouts_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_payouts_settlement
    FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_payouts_campaign_id ON payouts(campaign_id);
CREATE INDEX IF NOT EXISTS idx_payouts_settlement_id ON payouts(settlement_id);
CREATE INDEX IF NOT EXISTS idx_payouts_status ON payouts(status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_payouts_updated_at') THEN
    CREATE TRIGGER trg_payouts_updated_at
      BEFORE UPDATE ON payouts
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;
`;

export async function migratePayouts(options: DbTaskOptions = {}) {
  await pool.query(PAYOUTS_DDL);
  console.log("ForkUp payouts schema applied (payouts).");
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migratePayouts().catch((err) => {
    console.error("Payouts migration failed:", err);
    process.exit(1);
  });
}
