import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

/**
 * Additive migration: campaign gallery images (up to 6 enforced in app).
 * Does not alter campaigns.cover_image_url or any existing columns.
 */
const CAMPAIGN_IMAGES_DDL = `
CREATE TABLE IF NOT EXISTS campaign_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  image_url VARCHAR(512) NOT NULL,
  source VARCHAR(30) NOT NULL DEFAULT 'manual'
    CHECK (source IN (
      'manual',
      'website',
      'facebook',
      'instagram',
      'library',
      'social_suggest'
    )),
  source_url VARCHAR(512),
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_campaign_images_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_images_campaign_id
  ON campaign_images(campaign_id);

CREATE INDEX IF NOT EXISTS idx_campaign_images_campaign_sort
  ON campaign_images(campaign_id, sort_order);
`;

export async function migrateCampaignImages(options: DbTaskOptions = {}) {
  await pool.query(CAMPAIGN_IMAGES_DDL);
  console.log("ForkUp campaign_images schema applied.");
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateCampaignImages().catch((err) => {
    console.error("Campaign images migration failed:", err);
    process.exit(1);
  });
}
