/**
 * Additive migration: fundraiser ↔ nonprofit campaign invitations + campaign_fundraisers.
 *
 * Purpose: Let fundraisers propose campaigns for nonprofits they don't belong to.
 * Nonprofit accepts via email/dashboard (parallel to nonprofit_campaign_invitations).
 * After accept, nonprofit owns the campaign; fundraiser stays linked as co-organizer.
 *
 * Inputs: none (uses pool).
 * Outputs: fundraiser_campaign_invitations + campaign_fundraisers tables. Existing rows unchanged.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const FUNDRAISER_INVITES_DDL = `
CREATE TABLE IF NOT EXISTS fundraiser_campaign_invitations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(64) NOT NULL UNIQUE,
  fundraiser_user_id INTEGER NOT NULL,
  fundraiser_name VARCHAR(255),
  fundraiser_email VARCHAR(255) NOT NULL,
  nonprofit_id INTEGER NOT NULL,
  campaign_id INTEGER NOT NULL,
  invitation_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (invitation_status IN ('pending', 'accepted', 'declined')),
  message TEXT,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at TIMESTAMP,
  CONSTRAINT fk_fci_user
    FOREIGN KEY (fundraiser_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_fci_nonprofit
    FOREIGN KEY (nonprofit_id) REFERENCES nonprofits(id) ON DELETE CASCADE,
  CONSTRAINT fk_fci_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fci_nonprofit_status
  ON fundraiser_campaign_invitations(nonprofit_id, invitation_status);

CREATE INDEX IF NOT EXISTS idx_fci_fundraiser
  ON fundraiser_campaign_invitations(fundraiser_user_id);

CREATE TABLE IF NOT EXISTS campaign_fundraisers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'active', 'removed')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_campaign_fundraiser UNIQUE (campaign_id, user_id),
  CONSTRAINT fk_cf_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_cf_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_fundraisers_user
  ON campaign_fundraisers(user_id);
`;

export async function migrateFundraiserInvites(options: DbTaskOptions = {}) {
  await pool.query(FUNDRAISER_INVITES_DDL);
  console.log(
    "ForkUp fundraiser_campaign_invitations + campaign_fundraisers schema applied.",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateFundraiserInvites().catch((err) => {
    console.error("fundraiser invites migration failed:", err);
    process.exit(1);
  });
}
