/**
 * Additive migration: business paperwork fields + tokens table.
 * Mirrors columns present on local DB that had no prior migration file in-repo.
 *
 * Safe to re-run (IF NOT EXISTS).
 * Run: npx tsx src/legacy/db/migrate-business-paperwork.ts
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const SQL = `
ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS tax_id VARCHAR(30) NULL;

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS paperwork_status VARCHAR(20) NOT NULL DEFAULT 'pending';

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS paperwork_submitted_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS business_paperwork_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  token VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_business_paperwork_tokens_business
  ON business_paperwork_tokens (business_id);
`;

/**
 * Apply business paperwork columns + tokens table.
 * Inputs: none (uses pool).
 * Outputs: additive schema only; existing rows get paperwork_status='pending'.
 */
export async function migrateBusinessPaperwork(options: DbTaskOptions = {}) {
  await pool.query(SQL);
  console.log(
    "ForkUp business paperwork applied (businesses.tax_id/paperwork_* + business_paperwork_tokens).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateBusinessPaperwork().catch((err) => {
    console.error("business paperwork migration failed:", err);
    process.exit(1);
  });
}
