/**
 * Additive migration: 6-digit reset code for user forgot-password flow.
 *
 * Purpose: Extend password_reset_tokens so reset emails can include both a
 * long URL token (existing) and a short numeric code (Google-style enter-code).
 *
 * Inputs: none (DDL only).
 * Outputs: nullable `code` column + partial index. Existing rows stay valid (NULL).
 * Does not DROP/MODIFY/RENAME any existing columns or tables.
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const PASSWORD_RESET_CODE_DDL = `
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token VARCHAR(128) NOT NULL UNIQUE,
  code VARCHAR(10),
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE password_reset_tokens
  ADD COLUMN IF NOT EXISTS code VARCHAR(10);

CREATE INDEX IF NOT EXISTS idx_password_reset_user
  ON password_reset_tokens (user_id);

CREATE INDEX IF NOT EXISTS idx_password_reset_code
  ON password_reset_tokens (code)
  WHERE code IS NOT NULL;
`;

/**
 * Apply nullable reset-code column for user password recovery.
 *
 * Inputs: options.closePool — whether to end the pool (default true when run directly).
 * Outputs: void; logs success; additive only.
 */
export async function migratePasswordResetCode(options: DbTaskOptions = {}) {
  await pool.query(PASSWORD_RESET_CODE_DDL);
  console.log(
    "ForkUp password-reset code applied (password_reset_tokens.code nullable + index).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migratePasswordResetCode().catch((err) => {
    console.error("password-reset code migration failed:", err);
    process.exit(1);
  });
}
