/**
 * Additive migration — editable email templates (org / fundraiser / campaign).
 *
 * Purpose: Store role-scoped email subject/body library with optional campaign
 * override and default sender person. Platform SMTP address unchanged.
 *
 * Inputs: none (uses pool).
 * Outputs: email_templates table + partial unique indexes.
 *
 * Resolve order (app layer): campaign override → scope default → system hardcoded.
 * scope_type: nonprofit | business | fundraiser_user
 * scope_id: organization id OR fundraiser users.id
 */
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const EMAIL_TEMPLATES_DDL = `
CREATE TABLE IF NOT EXISTS email_templates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type VARCHAR(20) NOT NULL
    CHECK (scope_type IN ('nonprofit', 'business', 'fundraiser_user')),
  scope_id INTEGER NOT NULL,
  campaign_id INTEGER NULL,
  template_key VARCHAR(60) NOT NULL,
  name VARCHAR(255) NOT NULL,
  subject VARCHAR(500) NOT NULL,
  body TEXT NOT NULL,
  default_sender_user_id INTEGER NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by_user_id INTEGER NULL,
  updated_by_user_id INTEGER NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_email_templates_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_email_templates_default_sender
    FOREIGN KEY (default_sender_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_email_templates_created_by
    FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_email_templates_updated_by
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_email_templates_scope
  ON email_templates (scope_type, scope_id);

CREATE INDEX IF NOT EXISTS idx_email_templates_campaign
  ON email_templates (campaign_id)
  WHERE campaign_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_email_templates_scope_default
  ON email_templates (scope_type, scope_id, template_key)
  WHERE campaign_id IS NULL AND is_active = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_email_templates_scope_campaign
  ON email_templates (scope_type, scope_id, campaign_id, template_key)
  WHERE campaign_id IS NOT NULL AND is_active = TRUE;
`;

/**
 * Applies email_templates table migration.
 * Inputs: options.closePool — when false, leave pool open for chaining.
 * Outputs: table + indexes; logs confirmation.
 */
export async function migrateEmailTemplates(options: DbTaskOptions = {}) {
  await pool.query(EMAIL_TEMPLATES_DDL);
  console.log(
    "ForkUp email_templates applied (scope + optional campaign override).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateEmailTemplates().catch((err) => {
    console.error("email_templates migration failed:", err);
    process.exit(1);
  });
}
