import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const EMAIL_LOG_DDL = `
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS email_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER,
  recipient_email VARCHAR(255) NOT NULL,
  recipient_name VARCHAR(255),
  stakeholder_role VARCHAR(20)
    CHECK (stakeholder_role IN ('nonprofit','business','ambassador','supporter','admin')),
  email_type VARCHAR(60) NOT NULL,
  subject VARCHAR(512) NOT NULL,
  body TEXT NOT NULL,
  provider VARCHAR(20) NOT NULL DEFAULT 'ses'
    CHECK (provider IN ('ses','noop','smtp')),
  provider_message_id VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued','sent','failed','skipped')),
  error_message TEXT,
  related_token VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_email_log_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_email_log_campaign_id ON email_log(campaign_id);
CREATE INDEX IF NOT EXISTS idx_email_log_recipient ON email_log(recipient_email);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_email_log_updated_at') THEN
    CREATE TRIGGER trg_email_log_updated_at
      BEFORE UPDATE ON email_log
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;
`;

export async function migrateEmail(options: DbTaskOptions = {}) {
  await pool.query(EMAIL_LOG_DDL);
  console.log("ForkUp email schema applied (email_log).");
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateEmail().catch((err) => {
    console.error("Email migration failed:", err);
    process.exit(1);
  });
}
