import { ensureInvitationToken } from "../lib/invitations";
import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

const PATCH_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS invitation_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_business_location_id INTEGER NOT NULL UNIQUE,
    token VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tokens_cbl
      FOREIGN KEY (campaign_business_location_id) REFERENCES campaign_business_locations(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS business_acceptances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_business_location_id INTEGER NOT NULL UNIQUE,
    authorized_representative VARCHAR(255) NOT NULL,
    eligible_sales_rules TEXT NULL,
    forkup_fee_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    net7_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    ach_authorized BOOLEAN NOT NULL DEFAULT FALSE,
    billing_contact_name VARCHAR(255) NULL,
    billing_contact_email VARCHAR(255) NULL,
    settlement_contact_name VARCHAR(255) NULL,
    settlement_contact_email VARCHAR(255) NULL,
    change_request_message TEXT NULL,
    decline_reason TEXT NULL,
    accepted_at TIMESTAMP NULL,
    declined_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_acceptances_cbl
      FOREIGN KEY (campaign_business_location_id) REFERENCES campaign_business_locations(id) ON DELETE CASCADE
  )`,
];

export async function migratePatch(options: DbTaskOptions = {}) {
  for (const statement of PATCH_STATEMENTS) {
    await pool.query(statement);
  }

  await pool.query(
    `UPDATE businesses SET contact_email = 'ops@sovanabistro.com' WHERE slug = 'sovana-bistro' AND contact_email IS NULL`,
  );
  await pool.query(
    `UPDATE businesses SET contact_email = 'ops@thepear.com' WHERE slug = 'the-pear' AND contact_email IS NULL`,
  );

  const connection = await pool.connect();
  try {
    const { rows } = await connection.query<{ id: number }>(
      `SELECT cbl.id FROM campaign_business_locations cbl
       LEFT JOIN invitation_tokens it ON it.campaign_business_location_id = cbl.id
       WHERE it.id IS NULL`,
    );
    for (const row of rows) {
      await ensureInvitationToken(connection, Number(row.id));
    }
    console.log(`Backfilled ${rows.length} invitation token(s).`);
  } finally {
    connection.release();
  }

  console.log("Schema patch applied (invitation_tokens, business_acceptances).");
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migratePatch().catch((err) => {
    console.error("Patch failed:", err);
    process.exit(1);
  });
}
