import { isDirectRun, type DbTaskOptions } from "./cli";
import { pool } from "./pool";

/**
 * Additive settlement-engine columns + audit log.
 * Ported from ForkUpSettlementEngine (events/event_settlements/settlement_audit_log).
 */
const SETTLEMENT_ENGINE_DDL = `
ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS settlement_grace_days INTEGER NOT NULL DEFAULT 7;
ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS settlement_closed_at TIMESTAMP;
ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS settlement_frozen_at TIMESTAMP;
ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS adjustment_window_end TIMESTAMP;
ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS settlement_closed_by VARCHAR(100);

ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS snapshot_created_at TIMESTAMP;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS giveback_amount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS manual_donations DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS bartender_tips DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS silent_auction DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS stripe_donations DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS stripe_amount_charged DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS stripe_fee DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS stripe_net DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS platform_fee_percent DECIMAL(6,4) NOT NULL DEFAULT 0.15;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS ach_debit_amount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS ach_status VARCHAR(20) NOT NULL DEFAULT 'pending';
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS snapshot_status VARCHAR(40) NOT NULL DEFAULT 'pending';
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS pdf_business_path VARCHAR(1024);
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS pdf_nonprofit_path VARCHAR(1024);
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS pdf_internal_path VARCHAR(1024);
ALTER TABLE settlements
  ADD COLUMN IF NOT EXISTS pdf_ach_path VARCHAR(1024);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'settlements_ach_status_check'
  ) THEN
    ALTER TABLE settlements
      ADD CONSTRAINT settlements_ach_status_check
      CHECK (ach_status IN ('pending', 'processing', 'paid', 'failed'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'settlements_snapshot_status_check'
  ) THEN
    ALTER TABLE settlements
      ADD CONSTRAINT settlements_snapshot_status_check
      CHECK (snapshot_status IN ('pending', 'SNAPSHOT_CREATED', 'STATEMENTS_SENT'));
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS settlement_audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  settlement_id INTEGER,
  action VARCHAR(60) NOT NULL,
  old_status VARCHAR(40),
  new_status VARCHAR(40),
  performed_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
  details TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_settlement_audit_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_settlement_audit_settlement
    FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_settlement_audit_campaign_id
  ON settlement_audit_log(campaign_id);
CREATE INDEX IF NOT EXISTS idx_settlement_audit_action
  ON settlement_audit_log(campaign_id, action);
`;

export async function migrateSettlementEngine(options: DbTaskOptions = {}) {
  await pool.query(SETTLEMENT_ENGINE_DDL);
  console.log(
    "ForkUp settlement engine schema applied (campaign close/freeze columns, settlement snapshot columns, settlement_audit_log).",
  );
  if (options.closePool !== false) {
    await pool.end();
  }
}

if (isDirectRun(import.meta.url)) {
  migrateSettlementEngine().catch((err) => {
    console.error("Settlement engine migration failed:", err);
    process.exit(1);
  });
}
