-- ForkUp V1 PostgreSQL schema
-- Additive PostgreSQL equivalent of schema.sql, schema-foundation.sql,
-- and the profile columns currently applied by migrate-foundation.ts.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS nonprofits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  logo_url VARCHAR(512),
  mission TEXT,
  description TEXT,
  website VARCHAR(512),
  contact_name VARCHAR(255),
  contact_email VARCHAR(255),
  contact_phone VARCHAR(50),
  cause_category VARCHAR(100),
  ein VARCHAR(20),
  city VARCHAR(100),
  state VARCHAR(50),
  zip VARCHAR(20),
  verification_status VARCHAR(20) NOT NULL DEFAULT 'unclaimed'
    CHECK (verification_status IN ('unclaimed', 'claimed', 'verified', 'needs_review', 'archived')),
  claim_status VARCHAR(20) NOT NULL DEFAULT 'unclaimed'
    CHECK (claim_status IN ('unclaimed', 'claimed', 'verified', 'needs_review', 'archived')),
  facebook_url VARCHAR(512),
  instagram_url VARCHAR(512),
  linkedin_url VARCHAR(512),
  tiktok_url VARCHAR(512),
  youtube_url VARCHAR(512),
  profile_status VARCHAR(20) NOT NULL DEFAULT 'preloaded'
    CHECK (profile_status IN ('preloaded', 'invited', 'claimed', 'verified', 'active', 'inactive')),
  claimed_by_user_id INTEGER,
  claim_date TIMESTAMP,
  verification_date TIMESTAMP,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS businesses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  business_type VARCHAR(100),
  logo_url VARCHAR(512),
  description TEXT,
  website VARCHAR(512),
  default_giveback_percentage DECIMAL(5,2),
  contact_name VARCHAR(255),
  contact_email VARCHAR(255),
  contact_phone VARCHAR(50),
  supports_dine_and_donate BOOLEAN NOT NULL DEFAULT FALSE,
  supports_shop_and_donate BOOLEAN NOT NULL DEFAULT FALSE,
  supports_service_giveback BOOLEAN NOT NULL DEFAULT FALSE,
  supports_guest_bartending BOOLEAN NOT NULL DEFAULT FALSE,
  supports_ambassador_tracking BOOLEAN NOT NULL DEFAULT FALSE,
  business_status VARCHAR(20) NOT NULL DEFAULT 'preloaded'
    CHECK (business_status IN ('preloaded', 'invited', 'claimed', 'active', 'archived')),
  claim_status VARCHAR(20) NOT NULL DEFAULT 'unclaimed'
    CHECK (claim_status IN ('unclaimed', 'claimed', 'verified', 'needs_review', 'archived')),
  facebook_url VARCHAR(512),
  instagram_url VARCHAR(512),
  linkedin_url VARCHAR(512),
  tiktok_url VARCHAR(512),
  profile_status VARCHAR(30) NOT NULL DEFAULT 'preloaded'
    CHECK (profile_status IN ('preloaded', 'invited', 'claimed', 'verified', 'pending_onboarding', 'active', 'inactive')),
  claimed_by_user_id INTEGER,
  claim_date TIMESTAMP,
  verification_date TIMESTAMP,
  -- Pass C1: Join Us door (restaurant | local). Null for legacy rows.
  join_door_type VARCHAR(20) NULL
    CHECK (join_door_type IS NULL OR join_door_type IN ('restaurant', 'local')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS business_locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL,
  location_name VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(50),
  zip VARCHAR(20),
  phone VARCHAR(50),
  website_url VARCHAR(512),
  reservation_url VARCHAR(512),
  booking_url VARCHAR(512),
  active_status BOOLEAN NOT NULL DEFAULT TRUE,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_locations_business
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_business_locations_business_id
  ON business_locations(business_id);

CREATE INDEX IF NOT EXISTS idx_nonprofits_lat_lng
  ON nonprofits (latitude, longitude)
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_business_locations_lat_lng
  ON business_locations (latitude, longitude)
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

CREATE TABLE IF NOT EXISTS campaigns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(255) NOT NULL UNIQUE,
  nonprofit_id INTEGER NOT NULL,
  campaign_name VARCHAR(255) NOT NULL,
  campaign_story TEXT NOT NULL,
  campaign_goal INTEGER NOT NULL DEFAULT 0,
  campaign_start_date DATE,
  campaign_end_date DATE,
  campaign_status VARCHAR(30) NOT NULL DEFAULT 'draft'
    CHECK (campaign_status IN ('draft', 'in_review', 'invitation_phase', 'ready_to_launch', 'live', 'closed', 'settlement')),
  cover_image_url VARCHAR(2048) NOT NULL,
  -- Additive: optional YouTube watch/shorts URL for public hero (video first when set)
  featured_youtube_url VARCHAR(512),
  logo_url VARCHAR(512),
  raised INTEGER NOT NULL DEFAULT 0,
  supporters_going INTEGER NOT NULL DEFAULT 0,
  expected_guests INTEGER NOT NULL DEFAULT 0,
  verified_visits INTEGER NOT NULL DEFAULT 0,
  top_event BOOLEAN NOT NULL DEFAULT FALSE,
  terms_accepted BOOLEAN NOT NULL DEFAULT FALSE,
  terms_accepted_at TIMESTAMP,
  invitation_deadline DATE,
  -- Nick V2 Layer 2: Guest Bartending single event date + business timing / review gates
  event_date DATE,
  business_timing_status VARCHAR(40) NOT NULL DEFAULT 'ok'
    CHECK (business_timing_status IN (
      'ok',
      'needs_forkup_review',
      'limited_promotion_window',
      'tight_timeline',
      'too_soon'
    )),
  forkup_review_status VARCHAR(30) NOT NULL DEFAULT 'none'
    CHECK (forkup_review_status IN ('none', 'pending', 'approved', 'denied', 'changes_requested')),
  forkup_review_reason TEXT,
  forkup_review_requested_at TIMESTAMP,
  -- Timeline Check: organizer already has a business/venue confirmed (8–20 day band)
  confirmed_business_name VARCHAR(255),
  confirmed_contact_name VARCHAR(255),
  confirmed_contact_email VARCHAR(255),
  confirmed_method VARCHAR(30)
    CHECK (confirmed_method IS NULL OR confirmed_method IN ('email', 'phone', 'in_person')),
  confirmed_status VARCHAR(80),
  confirmed_notes TEXT,
  business_confirmed_at TIMESTAMP,
  created_by_user_id INTEGER,
  -- Settlement engine (ported from ForkUpSettlementEngine): grace + close + freeze
  settlement_grace_days INTEGER NOT NULL DEFAULT 7,
  settlement_closed_at TIMESTAMP,
  settlement_frozen_at TIMESTAMP,
  adjustment_window_end TIMESTAMP,
  settlement_closed_by VARCHAR(100),
  -- Settlement parity with old engine: NULL fees = platform defaults (15 / 2.9 / 0.30)
  platform_fee_percent DECIMAL(6,2),
  card_fee_percent DECIMAL(6,3),
  card_fee_fixed DECIMAL(10,2),
  bartender_tips DECIMAL(12,2) NOT NULL DEFAULT 0,
  silent_auction DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_campaigns_nonprofit
    FOREIGN KEY (nonprofit_id) REFERENCES nonprofits(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_campaigns_nonprofit_id ON campaigns(nonprofit_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(campaign_status);

-- Gallery images for public campaign pages (max 6 enforced in app). Additive only.
CREATE TABLE IF NOT EXISTS campaign_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  image_url VARCHAR(2048) NOT NULL,
  source VARCHAR(30) NOT NULL DEFAULT 'manual'
    CHECK (source IN (
      'manual',
      'website',
      'facebook',
      'instagram',
      'library',
      'social_suggest'
    )),
  source_url VARCHAR(2048),
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_campaign_images_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_images_campaign_id
  ON campaign_images(campaign_id);

CREATE INDEX IF NOT EXISTS idx_campaign_images_campaign_sort
  ON campaign_images(campaign_id, sort_order);

CREATE TABLE IF NOT EXISTS campaign_methods (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  method_type VARCHAR(40) NOT NULL
    CHECK (method_type IN (
      'dine_and_donate',
      'shop_and_donate',
      'service_giveback',
      'virtual_donations',
      'ambassador_fundraising',
      'guest_bartending_event'
    )),
  method_name VARCHAR(255) NOT NULL,
  method_start_date DATE,
  method_end_date DATE,
  method_status VARCHAR(30) NOT NULL DEFAULT 'draft'
    CHECK (method_status IN ('draft', 'invited', 'pending_acceptance', 'accepted', 'scheduled', 'live', 'completed', 'closed')),
  requires_business_acceptance BOOLEAN NOT NULL DEFAULT TRUE,
  -- Nick V2 Layer 2: per-method timing gate (30 / 21–29 / 8–20 / 0–7 bands)
  timing_status VARCHAR(40) NOT NULL DEFAULT 'ok'
    CHECK (timing_status IN (
      'ok',
      'needs_forkup_review',
      'limited_promotion_window',
      'tight_timeline',
      'too_soon'
    )),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_methods_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_methods_campaign_id ON campaign_methods(campaign_id);

CREATE TABLE IF NOT EXISTS campaign_business_locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  method_id INTEGER NOT NULL,
  business_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  invite_status VARCHAR(30) NOT NULL DEFAULT 'invited'
    CHECK (invite_status IN (
      'draft', 'invited', 'opened', 'pending', 'accepted', 'declined',
      'changes_requested', 'needs_info', 'ready', 'expired', 'live', 'completed'
    )),
  acceptance_status VARCHAR(30) NOT NULL DEFAULT 'invited'
    CHECK (acceptance_status IN (
      'draft', 'invited', 'opened', 'pending', 'accepted', 'declined',
      'changes_requested', 'needs_info', 'ready', 'expired', 'live', 'completed'
    )),
  giveback_percentage DECIMAL(5,2) NOT NULL,
  participation_start_date DATE,
  participation_end_date DATE,
  participation_hours VARCHAR(255),
  eligible_sales_rules TEXT,
  settlement_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (settlement_status IN ('pending', 'in_progress', 'completed')),
  terms_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  ach_authorized BOOLEAN NOT NULL DEFAULT FALSE,
  -- Nick V2 Layer 3: respond-by, open tracking, setup readiness
  respond_by_date DATE,
  opened_at TIMESTAMP,
  invited_by_user_id INTEGER,
  setup_status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (setup_status IN ('pending', 'needs_info', 'ready', 'complete')),
  marketing_ready_status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (marketing_ready_status IN ('pending', 'ready', 'blocked')),
  settlement_ready_status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (settlement_ready_status IN ('pending', 'needs_info', 'ready')),
  message_to_business TEXT,
  proposed_terms TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cbl_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_cbl_method
    FOREIGN KEY (method_id) REFERENCES campaign_methods(id) ON DELETE CASCADE,
  CONSTRAINT fk_cbl_business
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cbl_location
    FOREIGN KEY (location_id) REFERENCES business_locations(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_cbl_campaign_id ON campaign_business_locations(campaign_id);
CREATE INDEX IF NOT EXISTS idx_cbl_method_id ON campaign_business_locations(method_id);

CREATE TABLE IF NOT EXISTS supporters (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_supporters_email ON supporters(email);

CREATE TABLE IF NOT EXISTS participation_intents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  method_id INTEGER,
  business_id INTEGER,
  location_id INTEGER,
  supporter_id INTEGER NOT NULL,
  party_size INTEGER NOT NULL DEFAULT 1,
  is_first_visit BOOLEAN NOT NULL DEFAULT FALSE,
  participation_path VARCHAR(20) NOT NULL DEFAULT 'walk_in'
    CHECK (participation_path IN ('reservation', 'walk_in')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_intents_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_intents_supporter
    FOREIGN KEY (supporter_id) REFERENCES supporters(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_participation_intents_campaign_id
  ON participation_intents(campaign_id);

CREATE TABLE IF NOT EXISTS campaign_participants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  method_id INTEGER,
  participant_type VARCHAR(30) NOT NULL
    CHECK (participant_type IN ('ambassador', 'guest_bartender')),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  role_label VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'invited'
    CHECK (status IN ('invited', 'active', 'completed')),
  personal_share_link VARCHAR(512),
  tracking_code VARCHAR(100),
  leaderboard_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  business_id INTEGER,
  location_id INTEGER,
  event_date DATE,
  event_start_time TIME,
  event_end_time TIME,
  attributed_donation_total INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_participants_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  method_id INTEGER,
  business_id INTEGER,
  location_id INTEGER,
  supporter_id INTEGER,
  uploaded_image_url VARCHAR(512),
  ocr_status VARCHAR(20) NOT NULL DEFAULT 'uploaded'
    CHECK (ocr_status IN ('uploaded', 'processing', 'needs_review', 'approved', 'rejected')),
  review_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'approved', 'rejected')),
  subtotal DECIMAL(10,2),
  eligible_subtotal DECIMAL(10,2),
  donation_percentage DECIMAL(5,2),
  calculated_donation DECIMAL(10,2),
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at TIMESTAMP,
  CONSTRAINT fk_receipts_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS settlements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  business_id INTEGER,
  location_id INTEGER,
  eligible_sales DECIMAL(12,2) NOT NULL DEFAULT 0,
  donation_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
  donation_pool DECIMAL(12,2) NOT NULL DEFAULT 0,
  forkup_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_nonprofit_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_due_date DATE,
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (payment_status IN ('pending', 'invoiced', 'paid')),
  report_generated_at TIMESTAMP,
  locked_at TIMESTAMP,
  snapshot_created_at TIMESTAMP,
  giveback_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  manual_donations DECIMAL(12,2) NOT NULL DEFAULT 0,
  bartender_tips DECIMAL(12,2) NOT NULL DEFAULT 0,
  silent_auction DECIMAL(12,2) NOT NULL DEFAULT 0,
  stripe_donations DECIMAL(12,2) NOT NULL DEFAULT 0,
  stripe_amount_charged DECIMAL(12,2) NOT NULL DEFAULT 0,
  stripe_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  stripe_net DECIMAL(12,2) NOT NULL DEFAULT 0,
  platform_fee_percent DECIMAL(6,4) NOT NULL DEFAULT 0.15,
  ach_debit_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  ach_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (ach_status IN ('pending', 'processing', 'paid', 'failed')),
  snapshot_status VARCHAR(40) NOT NULL DEFAULT 'pending'
    CHECK (snapshot_status IN ('pending', 'SNAPSHOT_CREATED', 'STATEMENTS_SENT')),
  pdf_business_path VARCHAR(1024),
  pdf_nonprofit_path VARCHAR(1024),
  pdf_internal_path VARCHAR(1024),
  pdf_ach_path VARCHAR(1024),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_settlements_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS settlement_audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  settlement_id INTEGER,
  action VARCHAR(60) NOT NULL,
  old_status VARCHAR(40),
  new_status VARCHAR(40),
  performed_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
  details TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_settlement_audit_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_settlement_audit_settlement
    FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_settlement_audit_campaign_id
  ON settlement_audit_log(campaign_id);
CREATE INDEX IF NOT EXISTS idx_settlement_audit_action
  ON settlement_audit_log(campaign_id, action);

CREATE TABLE IF NOT EXISTS success_engine_actions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  action_type VARCHAR(40) NOT NULL
    CHECK (action_type IN (
      'launch_email',
      'one_week_reminder',
      'mid_campaign_reminder',
      'final_push_reminder',
      'results_email',
      'ambassador_recruitment',
      'guest_bartender_recruitment',
      'business_promotion',
      'receipt_reminder',
      'business_invite_reminder',
      'nonprofit_announcement',
      'staff_talking_points',
      'social_post',
      'countdown_reminder',
      'day_of_reminder',
      'thank_you',
      'settlement_recap',
      'rebooking_prompt',
      'admin_review_summary'
    )),
  channel VARCHAR(20) NOT NULL DEFAULT 'email'
    CHECK (channel IN ('email', 'text', 'social')),
  scheduled_date DATE,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'ready', 'completed')),
  stakeholder_role VARCHAR(20)
    CHECK (stakeholder_role IS NULL OR stakeholder_role IN (
      'nonprofit', 'business', 'ambassador', 'supporter', 'admin'
    )),
  generated_by VARCHAR(20) NOT NULL DEFAULT 'system'
    CHECK (generated_by IN ('system', 'ai', 'manual')),
  completed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_success_actions_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

-- Nick V2 Layer 4: AI guidance / health / review insight log
CREATE TABLE IF NOT EXISTS campaign_ai_insights (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  insight_type VARCHAR(40) NOT NULL
    CHECK (insight_type IN (
      'timing_guidance',
      'method_mix',
      'invite_readiness',
      'business_recommendations',
      'health_nudge',
      'admin_review',
      'settlement_narrative',
      'calendar_plan'
    )),
  score INTEGER,
  summary TEXT NOT NULL,
  payload_json JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_insights_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_ai_insights_campaign
  ON campaign_ai_insights(campaign_id);

CREATE INDEX IF NOT EXISTS idx_success_engine_campaign_id
  ON success_engine_actions(campaign_id);

CREATE TABLE IF NOT EXISTS invitation_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_business_location_id INTEGER NOT NULL UNIQUE,
  token VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tokens_cbl
    FOREIGN KEY (campaign_business_location_id)
    REFERENCES campaign_business_locations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS business_acceptances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_business_location_id INTEGER NOT NULL UNIQUE,
  authorized_representative VARCHAR(255) NOT NULL,
  eligible_sales_rules TEXT,
  forkup_fee_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  net7_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  ach_authorized BOOLEAN NOT NULL DEFAULT FALSE,
  billing_contact_name VARCHAR(255),
  billing_contact_email VARCHAR(255),
  settlement_contact_name VARCHAR(255),
  settlement_contact_email VARCHAR(255),
  change_request_message TEXT,
  decline_reason TEXT,
  accepted_at TIMESTAMP,
  declined_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_acceptances_cbl
    FOREIGN KEY (campaign_business_location_id)
    REFERENCES campaign_business_locations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  full_name VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organization_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_type VARCHAR(20) NOT NULL
    CHECK (organization_type IN ('nonprofit', 'business')),
  organization_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'admin'
    CHECK (role IN ('owner', 'admin', 'manager', 'viewer')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_org_user UNIQUE (organization_type, organization_id, user_id),
  CONSTRAINT fk_org_users_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_org_users_org
  ON organization_users(organization_type, organization_id);

CREATE TABLE IF NOT EXISTS donations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  method_id INTEGER,
  supporter_id INTEGER,
  campaign_participant_id INTEGER,
  amount DECIMAL(12,2) NOT NULL,
  donation_type VARCHAR(30) NOT NULL DEFAULT 'virtual'
    CHECK (donation_type IN ('virtual', 'manual', 'offline_adjustment')),
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (payment_status IN ('pending', 'completed', 'failed')),
  attribution_code VARCHAR(100),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_donations_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_donations_campaign_id ON donations(campaign_id);

CREATE TABLE IF NOT EXISTS organization_imports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_type VARCHAR(20) NOT NULL
    CHECK (organization_type IN ('nonprofit', 'business')),
  organization_id INTEGER NOT NULL,
  import_type VARCHAR(30) NOT NULL
    CHECK (import_type IN ('csv', 'contacts', 'assets', 'pdf', 'url', 'campaign_history', 'integration')),
  source_label VARCHAR(255),
  review_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'approved', 'rejected')),
  payload_json JSON,
  campaign_id INTEGER,
  imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_org_imports_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_org_imports_org
  ON organization_imports(organization_type, organization_id);

CREATE TABLE IF NOT EXISTS business_invitations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  nonprofit_id INTEGER NOT NULL,
  method_id INTEGER NOT NULL,
  business_id INTEGER,
  business_name VARCHAR(255) NOT NULL,
  business_email VARCHAR(255) NOT NULL,
  invitation_status VARCHAR(20) NOT NULL DEFAULT 'sent'
    CHECK (invitation_status IN (
      'draft', 'sent', 'invited', 'opened', 'accepted', 'declined',
      'expired', 'needs_info', 'ready', 'live', 'completed'
    )),
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at TIMESTAMP,
  respond_by_date DATE,
  opened_at TIMESTAMP,
  invited_by_user_id INTEGER,
  campaign_business_location_id INTEGER,
  proposed_giveback_percentage DECIMAL(5,2),
  proposed_terms TEXT,
  message_to_business TEXT,
  accepted_at TIMESTAMP,
  decline_reason TEXT,
  setup_status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (setup_status IN ('pending', 'needs_info', 'ready', 'complete')),
  marketing_ready_status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (marketing_ready_status IN ('pending', 'ready', 'blocked')),
  settlement_ready_status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (settlement_ready_status IN ('pending', 'needs_info', 'ready')),
  CONSTRAINT fk_bi_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_bi_nonprofit
    FOREIGN KEY (nonprofit_id) REFERENCES nonprofits(id) ON DELETE CASCADE,
  CONSTRAINT fk_bi_method
    FOREIGN KEY (method_id) REFERENCES campaign_methods(id) ON DELETE CASCADE,
  CONSTRAINT fk_bi_business
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
  CONSTRAINT fk_bi_cbl
    FOREIGN KEY (campaign_business_location_id)
    REFERENCES campaign_business_locations(id) ON DELETE SET NULL
);

-- Existing DBs may have created business_invitations before business_id existed.
-- CREATE TABLE IF NOT EXISTS does not add columns; ensure the column exists before indexes/FKs.
ALTER TABLE business_invitations
  ADD COLUMN IF NOT EXISTS business_id INTEGER;

CREATE INDEX IF NOT EXISTS idx_business_invitations_campaign
  ON business_invitations(campaign_id);
CREATE INDEX IF NOT EXISTS idx_business_invitations_business_id
  ON business_invitations(business_id);
CREATE INDEX IF NOT EXISTS idx_business_invitations_status
  ON business_invitations(invitation_status);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_auth_sessions_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id);

CREATE TABLE IF NOT EXISTS nonprofit_campaign_invitations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(64) NOT NULL UNIQUE,
  business_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  nonprofit_id INTEGER NOT NULL,
  campaign_id INTEGER NOT NULL,
  method_id INTEGER NOT NULL,
  method_type VARCHAR(40) NOT NULL
    CHECK (method_type IN ('dine_and_donate', 'shop_and_donate', 'service_giveback', 'guest_bartending_event')),
  giveback_percentage DECIMAL(5,2) NOT NULL DEFAULT 10,
  invitation_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (invitation_status IN ('pending', 'accepted', 'declined')),
  message TEXT,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at TIMESTAMP,
  CONSTRAINT fk_nci_business
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
  CONSTRAINT fk_nci_location
    FOREIGN KEY (location_id) REFERENCES business_locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_nci_nonprofit
    FOREIGN KEY (nonprofit_id) REFERENCES nonprofits(id) ON DELETE CASCADE,
  CONSTRAINT fk_nci_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_nci_method
    FOREIGN KEY (method_id) REFERENCES campaign_methods(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_nci_nonprofit
  ON nonprofit_campaign_invitations(nonprofit_id, invitation_status);

-- Fundraiser → nonprofit campaign invitations (co-organizer; NP owns after accept).
CREATE TABLE IF NOT EXISTS fundraiser_campaign_invitations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(64) NOT NULL UNIQUE,
  fundraiser_user_id INTEGER NOT NULL,
  fundraiser_name VARCHAR(255),
  fundraiser_email VARCHAR(255) NOT NULL,
  nonprofit_id INTEGER NOT NULL,
  campaign_id INTEGER NOT NULL,
  invitation_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (invitation_status IN ('pending', 'accepted', 'declined')),
  message TEXT,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at TIMESTAMP,
  CONSTRAINT fk_fci_user
    FOREIGN KEY (fundraiser_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_fci_nonprofit
    FOREIGN KEY (nonprofit_id) REFERENCES nonprofits(id) ON DELETE CASCADE,
  CONSTRAINT fk_fci_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fci_nonprofit_status
  ON fundraiser_campaign_invitations(nonprofit_id, invitation_status);

CREATE INDEX IF NOT EXISTS idx_fci_fundraiser
  ON fundraiser_campaign_invitations(fundraiser_user_id);

CREATE TABLE IF NOT EXISTS campaign_fundraisers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'active', 'removed')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_campaign_fundraiser UNIQUE (campaign_id, user_id),
  CONSTRAINT fk_cf_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_cf_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_fundraisers_user
  ON campaign_fundraisers(user_id);

CREATE TABLE IF NOT EXISTS organization_access_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_type VARCHAR(20) NOT NULL
    CHECK (organization_type IN ('nonprofit', 'business')),
  organization_id INTEGER,
  organization_name VARCHAR(255),
  request_type VARCHAR(20) NOT NULL DEFAULT 'claim'
    CHECK (request_type IN ('claim', 'access')),
  risk_level VARCHAR(20) NOT NULL DEFAULT 'low'
    CHECK (risk_level IN ('low', 'medium', 'high')),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'denied')),
  requested_by_user_id INTEGER,
  requester_name VARCHAR(255),
  requester_email VARCHAR(255),
  relationship VARCHAR(255),
  risk_reason TEXT,
  reviewed_by_user_id INTEGER,
  reviewed_at TIMESTAMP,
  review_notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_access_requests_org
  ON organization_access_requests(organization_type, organization_id);
CREATE INDEX IF NOT EXISTS idx_access_requests_status
  ON organization_access_requests(status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_nonprofits_updated_at') THEN
    CREATE TRIGGER trg_nonprofits_updated_at
      BEFORE UPDATE ON nonprofits
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_businesses_updated_at') THEN
    CREATE TRIGGER trg_businesses_updated_at
      BEFORE UPDATE ON businesses
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_business_locations_updated_at') THEN
    CREATE TRIGGER trg_business_locations_updated_at
      BEFORE UPDATE ON business_locations
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_campaigns_updated_at') THEN
    CREATE TRIGGER trg_campaigns_updated_at
      BEFORE UPDATE ON campaigns
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_campaign_methods_updated_at') THEN
    CREATE TRIGGER trg_campaign_methods_updated_at
      BEFORE UPDATE ON campaign_methods
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_cbl_updated_at') THEN
    CREATE TRIGGER trg_cbl_updated_at
      BEFORE UPDATE ON campaign_business_locations
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_business_acceptances_updated_at') THEN
    CREATE TRIGGER trg_business_acceptances_updated_at
      BEFORE UPDATE ON business_acceptances
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_users_updated_at') THEN
    CREATE TRIGGER trg_users_updated_at
      BEFORE UPDATE ON users
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_org_access_requests_updated_at') THEN
    CREATE TRIGGER trg_org_access_requests_updated_at
      BEFORE UPDATE ON organization_access_requests
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;

-- AI-first create flow: backend analyze (Steps 3–4) + Step 5 idea cards.
-- Guest campaign draft body stays in browser localStorage (not stored here).
CREATE TABLE IF NOT EXISTS organization_ai_analysis_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_token VARCHAR(64) NOT NULL UNIQUE,
  nonprofit_id INTEGER NULL,
  organization_name VARCHAR(255) NOT NULL,
  ein VARCHAR(20),
  website VARCHAR(512),
  facebook_url VARCHAR(512),
  instagram_url VARCHAR(512),
  linkedin_url VARCHAR(512),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  analysis_json JSON,
  error_message TEXT,
  created_by_user_id INTEGER NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_org_ai_analysis_nonprofit
    FOREIGN KEY (nonprofit_id) REFERENCES nonprofits(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_org_ai_analysis_token
  ON organization_ai_analysis_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_org_ai_analysis_nonprofit
  ON organization_ai_analysis_sessions(nonprofit_id);
CREATE INDEX IF NOT EXISTS idx_org_ai_analysis_expires
  ON organization_ai_analysis_sessions(expires_at);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_org_ai_analysis_updated_at'
  ) THEN
    CREATE TRIGGER trg_org_ai_analysis_updated_at
      BEFORE UPDATE ON organization_ai_analysis_sessions
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS organization_ai_campaign_ideas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_session_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  confidence INTEGER NOT NULL DEFAULT 0
    CHECK (confidence >= 0 AND confidence <= 100),
  thumbnail_url VARCHAR(512),
  suggested_goal NUMERIC(12, 2),
  suggested_methods JSON,
  payload_json JSON,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_org_ai_ideas_session
    FOREIGN KEY (analysis_session_id)
    REFERENCES organization_ai_analysis_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_org_ai_ideas_session
  ON organization_ai_campaign_ideas(analysis_session_id, sort_order);
